print("=========================")
print()
print("BEST FRIEND MAKER")
print()
print("=========================")
print()
print()
print("Hi. I'm the computer.")
first_name = input("What's your name? ")
fcolour = input(f"Hi, {first_name}! What's your favorite color? ")
print(f"No way! My favorite color is also {fcolour}!")
fmovie = input("What's your favorite movie? ")
print(f"What!?! My favorite movie is also {fmovie}! ")
fsport = input("What is your favorite game? ")
print(f"Get out of here! My favorite game is {fsport}, too!")
ltopping = input("What is your LEAST favorite pizza topping? ")
print(f"I dislike {ltopping} on py pizza! Just like you!")
fclass = input("What is your favorite class? ")
print(f"Wow! My favorite class is {fclass}, as well!")
print("We like all the same things! We should become best friends")